spring:
  jpa:
    show_sql: true
    properties:
      hibernate:
        dialect:
    hibernate:
      ddl-auto: create
  profiles:
    include: google
  session:
    store-type: jdbc

  h2:
    console:
      enabled: true
