spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/book-test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
  profiles:
    include: google
  session:
    store-type: jdbc